### ISSUE TITLE
ferm callout get_private_subnets.py error when using oz w/openvpn

### ISSUE THREAD

**Issue by dma** [subgraph/subgraph-os-issues#273]
Sep  4 03:45:25 subgraph ferm[11465]: Reloading Firewall configuration...Traceback (most recent call last):
Sep  4 03:45:25 subgraph ferm[11465]:   File "/usr/lib/subgraph-ferm-config/get_private_subnets.py", line 60, in <module>
Sep  4 03:45:25 subgraph ferm[11465]:     print "\n".join( get_private_subnets(addrs) )
Sep  4 03:45:25 subgraph ferm[11465]:   File "/usr/lib/subgraph-ferm-config/get_private_subnets.py", line 40, in get_private_subnets
Sep  4 03:45:25 subgraph ferm[11465]:     addr, maskbits = addr.split('/')
Sep  4 03:45:25 subgraph ferm[11465]: ValueError: need more than 1 value to unpack
Sep  4 03:45:25 subgraph ferm[11465]: .
Sep  4 03:45:25 subgraph systemd[1]: Reloaded ferm firewall configuration.

**Comment by mckinney-subgraph** [comment]
Need more info. What is the input to the script in this situation?

**Comment by dma** [comment]
It happens whenever openvpn client starts. I imagine you can reproduce this immediately if you configure an oz OpenVPN sandbox. I'll provide you with access if required.

```
Oct  1 01:54:56 subgraph openvpn[6029]: TUN/TAP device tun0 opened
Oct  1 01:54:56 subgraph openvpn[6029]: do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Oct  1 01:54:56 subgraph openvpn[6029]: /sbin/ip link set dev tun0 up mtu 1500
Oct  1 01:54:56 subgraph openvpn[6029]: /sbin/ip addr add dev tun0 local 10.15.10.6 peer 10.15.10.5
Oct  1 01:54:56 subgraph openvpn[6029]: Initialization Sequence Completed
Oct  1 01:54:57 subgraph dbus[701]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Oct  1 01:54:57 subgraph systemd[1]: Starting Network Manager Script Dispatcher Service...
Oct  1 01:54:57 subgraph dbus[701]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Oct  1 01:54:57 subgraph systemd[1]: Started Network Manager Script Dispatcher Service.
Oct  1 01:54:57 subgraph nm-dispatcher: req:1 'up' [tun0]: new request (2 scripts)
Oct  1 01:54:57 subgraph nm-dispatcher: req:1 'up' [tun0]: start running ordered scripts...
Oct  1 01:54:57 subgraph systemd[1]: Reloading ferm firewall configuration.
Oct  1 01:54:58 subgraph ferm[6218]: Reloading Firewall configuration...Traceback (most recent call last):
Oct  1 01:54:58 subgraph ferm[6218]:   File "/usr/lib/subgraph-ferm-config/get_private_subnets.py", line 60, in <module>
Oct  1 01:54:58 subgraph ferm[6218]:     print "\n".join( get_private_subnets(addrs) )
Oct  1 01:54:58 subgraph ferm[6218]:   File "/usr/lib/subgraph-ferm-config/get_private_subnets.py", line 40, in get_private_subnets
Oct  1 01:54:58 subgraph ferm[6218]:     addr, maskbits = addr.split('/')
Oct  1 01:54:58 subgraph ferm[6218]: ValueError: need more than 1 value to unpack
Oct  1 01:54:58 subgraph ferm[6218]: .
Oct  1 01:54:58 subgraph systemd[1]: Reloaded ferm firewall configuration.
```
