### ISSUE TITLE
Can't start torbrowser

### ISSUE THREAD

**Issue by trouat** [subgraph/subgraph-os-issues#328]
Hello,

From fresh install and updated system, I start "torbrowser-launcher" and I get the tarball and wait for install process: never terminate. I have tried several times since the beginning with each time the same result.

I clic on "cancel" button after two hour, and reboot system. I clic directly on the "tor browser" button from the application menu. After that, no effect.

```
/var/log/message:
Feb 11 10:26:21 subgraph torbrowser.desktop[1794]: ok received from application launch request
```

```
/var/log/syslog:
Feb 11 10:26:21 subgraph oz-daemon[1009]: 2018/02/11 10:26:21 Launch message received. Path: /usr/bin/torbrowser-launcher Name:  Pwd: /home/user Args: []
Feb 11 10:26:21 subgraph oz-daemon[1009]: 2018/02/11 10:26:21 Execution request from uid 1000, gid 1000
Feb 11 10:26:21 subgraph oz-daemon[1009]: 2018/02/11 10:26:21 Found running sandbox for `torbrowser-launcher`, running program there
Feb 11 10:26:21 subgraph oz-daemon[1009]: 2018/02/11 10:26:21 [torbrowser-launcher] Run program message received: &{Args:[] Pwd:/home/user Path:/usr/bin/torbrowser-launcher}
Feb 11 10:26:21 subgraph oz-daemon[1009]: 2018/02/11 10:26:21 [torbrowser-launcher] Enabling seccomp whitelist for: /usr/bin-oz/torbrowser-launcher
Feb 11 10:26:21 subgraph torbrowser.desktop[1794]: ok received from application launch request
Feb 11 10:26:22 subgraph oz-daemon[1009]: 2018/02/11 10:26:22 [torbrowser-launcher] Child process pid=125 exited from init with status 0
Feb 11 10:26:22 subgraph oz-daemon[1009]: 2018/02/11 10:26:22 [torbrowser-launcher] Child process pid=126 exited from init with status -1
Feb 11 10:26:27 subgraph oz-daemon[1009]: 2018/02/11 10:26:27 [torbrowser-launcher] (stderr) Traceback (most recent call last):
Feb 11 10:26:27 subgraph oz-daemon[1009]: 2018/02/11 10:26:27 [torbrowser-launcher] (stderr)   File "/usr/bin-oz/torbrowser-launcher", line 30, in <module>
Feb 11 10:26:27 subgraph oz-daemon[1009]: 2018/02/11 10:26:27 [torbrowser-launcher] (stderr)     torbrowser_launcher.main()
Feb 11 10:26:27 subgraph oz-daemon[1009]: 2018/02/11 10:26:27 [torbrowser-launcher] (stderr)   File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 62, in main
Feb 11 10:26:27 subgraph oz-daemon[1009]: 2018/02/11 10:26:27 [torbrowser-launcher] (stderr)     app = Launcher(common, url_list)
Feb 11 10:26:27 subgraph oz-daemon[1009]: 2018/02/11 10:26:27 [torbrowser-launcher] (stderr)   File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 91, in __init__
Feb 11 10:26:27 subgraph oz-daemon[1009]: 2018/02/11 10:26:27 [torbrowser-launcher] (stderr)     if not self.common.settings['installed'] or not self.check_min_version():
Feb 11 10:26:27 subgraph oz-daemon[1009]: 2018/02/11 10:26:27 [torbrowser-launcher] (stderr)   File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 603, in check_min_version
Feb 11 10:26:27 subgraph oz-daemon[1009]: 2018/02/11 10:26:27 [torbrowser-launcher] (stderr)     for line in open(self.common.paths['tbb']['versions']).readlines():
Feb 11 10:26:27 subgraph oz-daemon[1009]: 2018/02/11 10:26:27 [torbrowser-launcher] (stdout) Tor Browser Launcher
Feb 11 10:26:27 subgraph oz-daemon[1009]: 2018/02/11 10:26:27 [torbrowser-launcher] (stdout) By Micah Lee, licensed under MIT
Feb 11 10:26:27 subgraph oz-daemon[1009]: 2018/02/11 10:26:27 [torbrowser-launcher] (stdout) version 0.2.8
Feb 11 10:26:27 subgraph oz-daemon[1009]: 2018/02/11 10:26:27 [torbrowser-launcher] (stdout) https://github.com/micahflee/torbrowser-launcher
Feb 11 10:26:27 subgraph oz-daemon[1009]: 2018/02/11 10:26:27 [torbrowser-launcher] (stdout) Refreshing local keyring...
Feb 11 10:26:27 subgraph oz-daemon[1009]: 2018/02/11 10:26:27 [torbrowser-launcher] (stderr) IOError: [Errno 2] Aucun fichier ou dossier de ce type: '/home/user/.local/share/torbrowser/tbb/x86_64/tor-browser_fr/Browser/TorBrowser/Docs/sources/versions'
Feb 11 10:26:27 subgraph oz-daemon[1009]: 2018/02/11 10:26:27 [torbrowser-launcher] Child process pid=104 exited from init with status 1
```

Note: with the following commands, the browser starts
```
cd ~/.local/share/torbrowser/tbb/x86_64/tor-browser_fr/Browser
./start-tor-browser
```
The browser notice having a problem with tor. However tests show that it works ...

Thank you for your great work.

**Comment by burdges** [comment]
I think if tor browser is started like that then it cannot access the control port so it will not work properly.

**Comment by mckinney-subgraph** [comment]
I have put the torbrowser-launcher from stretch-backports into our apt repo. This should fix the problem. On a fresh install, the recommended `apt-get update/upgrade/dist-upgrade` dance should be sufficient.

**Comment by burdges** [comment]
Yup, works now, thanks!  

Just fyi, there is a separate issue that `sudo systemctl restart tor` causes the onion system tray icon to remain permanently grayed out, although Tor browser itself finds the new tor daemon correctly.  I think `sudo killall -HUP tor` does not cause this problem, but that frequently does not suffice to keep tor running under bad network conditions, like say home fiber connections in France.  ;)

**Comment by trouat** [comment]
Thank you, it’s done.

**Comment by trouat** [comment]
Thank you. it works very well with the package update.
