### ISSUE TITLE
hexchat seccomp

### ISSUE THREAD

**Issue by aaf1de1e76c9425817f5045684594e6d** [subgraph/subgraph-os-issues#83]
hexchat oz profile seems to break:

audit: type=1326 audit(1455472006.821:70): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=6270 comm="hexchat" exe="/usr/bin-oz/hexchat" sig=31 arch=c000003e syscall=307 compat=0 ip=0x350aae94f29 code=0x0
audit: type=1326 audit(1455472009.153:71): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=6196 comm="hexchat" exe="/usr/bin-oz/hexchat" sig=31 arch=c000003e syscall=72 compat=0 ip=0x350ab15e8c2 code=0x0

**Comment by aaf1de1e76c9425817f5045684594e6d** [comment]
I had to add these 3 otherwise any file dialog boxes cause hexchat to lock up.

getcwd:1
fallocate:1
getrusage:1

**Comment by znd0e2sknte** [comment]
I too was having this issue, except the whole of gdm was locking up.
Adding fallocate:1 (getcwd and getrusage was already set) stopped gdm from crashing entirely.

However, when connecting to a server hexchat (and only hexchat) crashes halfway through the server message.

 I have attached the journalctl hexchat related output in the attached file.

**Comment by znd0e2sknte** [comment]
eh attachment didnt work - output of journalctl:

Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 Launch message received. Path: /usr/bin/hexchat Name:  Pwd: /home/user Args: [--existing]
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 Would launch hexchat
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Init state: &{Profile:{Name:hexchat Path:/usr/bin/hexchat Paths:[] ProfilePath: DefaultParams:[--no-plugins] AutoShutdown:yes Watchdog:[] Wrapper: Multi:false NoSysProc:false NoDefaults:false AllowFiles:false AllowedGroups:[] Whitelist:[{Path:${HOME}/.config/hexchat Target: ReadOnly:false CanCreate:true Ignore:false Force:false NoFollow:false} {Path:/var/lib/oz/cells.d/hexchat.json Target: ReadOnly:true CanCreate:false Ignore:false Force:false NoFollow:false} {Path:/var/lib/oz/cells.d/hexchat-whitelist.seccomp Target: ReadOnly:true CanCreate:false Ignore:false Force:false NoFollow:false}] Blacklist:[] XServer:{Enabled:true TrayIcon:/usr/share/icons/hicolor/scalable/apps/hexchat.svg WindowIcon: EnableTray:false EnableNotifications:true DisableClipboard:false AudioMode:none PulseAudio:false Border:false} Environment:[] Networking:{Nettype:empty Sockets:[{Nettype:client Proto:tcp Port:9050 Destination:}] IpByte:0 DNSMode:} Seccomp:{Mode:whitelist Enforce:true Debug:false Train:false TrainOutput: Whitelist:/var/lib/oz/cells.d/hexchat-whitelist.seccomp Blacklist: ExtraDefs:[]} ExternalForwarders:[]} Config:{ProfileDir:/var/lib/oz/cells.d ShellPath:/bin/bash PrefixPath:/usr EtcPrefix:/etc/oz SandboxPath:/srv/oz BridgeMACAddr:6A:A8:2E:56:E8:9C DivertSuffix: DivertPath:true NMIgnoreFile:/etc/NetworkManager/conf.d/oz.conf UseFullDev:false AllowRootShell:false LogXpra:true EnvironmentVars:[USER USERNAME LOGNAME LANG LANGUAGE _ TZ=UTC XDG_SESSION_TYPE XDG_RUNTIME_DIR XDG_DATA_DIRS XDG_SEAT XDG_SESSION_TYPE XDG_SESSION_ID] DefaultGroups:[audio video]} Sockaddr:/srv/oz/sockets/oz-init-control-ec8ec83c32665e49 LaunchEnv:[USER=user USERNAME=user LOGNAME=user LANG=en_US.UTF-8 TZ=UTC XDG_SESSION_TYPE=x11 XDG_RUNTIME_DIR=/run/user/1000 XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share/:/usr/share/ XDG_SEAT=seat0 XDG_SESSION_TYPE=x11 XDG_SESSION_ID=2] Uid:1000 Gid:1000 Gids:map[audio:29 video:44] User:{Uid:1000 Gid:1000 Username:user Name:User HomeDir:/home/user} Network:{Interface:<nil> VethHost: VethGu
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 oz-init (hexchat) is waiting for init
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Recieved SIGUSR1 from parent (user defined signal 1), ready to init.
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Starting oz-init for profile: hexchat
Apr 18 02:44:11 subgraph hexchat.desktop[2844]: ok received
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] bind mounting (as readonly) /bin -> /srv/oz/rootfs/bin
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] bind mounting (as readonly) /lib -> /srv/oz/rootfs/lib
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] bind mounting (as readonly) /lib64 -> /srv/oz/rootfs/lib64
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] bind mounting (as readonly) /usr -> /srv/oz/rootfs/usr
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] bind mounting (as readonly) /etc -> /srv/oz/rootfs/etc
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Blacklisted path: /oz.ro.dir -> /usr/lib/gvfs
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Blacklisted path: /oz.ro.dir -> /usr/sbin
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Blacklisted path: /oz.ro.dir -> /sbin
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Blacklisted path: /oz.ro.file -> /etc/machine-id
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Blacklisted path: /oz.ro.file -> /etc/shadow
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Blacklisted path: /oz.ro.file -> /etc/shadow-
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Blacklisted path: /oz.ro.file -> /usr/bin/sudo
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Blacklisted path: /oz.ro.file -> /bin/su
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Blacklisted path: /oz.ro.file -> /bin/mount
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Blacklisted path: /oz.ro.file -> /bin/umount
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Blacklisted path: /oz.ro.file -> /bin/fusermount
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] bind mounting  /home/user/.config/hexchat -> /srv/oz/rootfs/home/user/.config/hexchat
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] bind mounting (as readonly) /var/lib/oz/cells.d/hexchat.json -> /srv/oz/rootfs/var/lib/oz/cells.d/hexchat.json
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] bind mounting (as readonly) /var/lib/oz/cells.d/hexchat-whitelist.seccomp -> /srv/oz/rootfs/var/lib/oz/cells.d/hexchat-whitelist.seccomp
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] bind mounting  /home/user/.Xoz/hexchat -> /srv/oz/rootfs/home/user/.Xoz/hexchat
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] chroot to /srv/oz/rootfs
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Mounting /dev/pts [devpts]
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Mounting /proc [proc]
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Mounting /sys [sysfs]
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] -------------------------------------------------------------------
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Interface      IP                            Mask            Status
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] lo             127.0.0.1/8                   255.0.0.0       up
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] -------------------------------------------------------------------
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Hostname set to (hexchat.local)
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] dbus-uuid: 43ce67e6343a1bbb0af5c7b858f57d7b
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] xpra work dir is /home/user/.Xoz/hexchat
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] Starting xpra server
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] (xpra-server) I /usr/bin/xpra [/usr/bin/xpra --no-daemon --mmap --no-sharing --bell --system-tray --xsettings --cursors --encoding=rgb --clipboard --no-microphone --no-speaker --notifications --no-mdns --input-method=keep --bind=/home/user/.Xoz/hexchat --socket-dir=/home/user/.Xoz/hexchat start :0]
Apr 18 02:44:11 subgraph oz-daemon[1042]: 2017/04/18 02:44:11 [hexchat] (xpra-server) Warning: invalid option: 'html'
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) WARNING: low display number: 0
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) You are attempting to run the xpra server against what seems to be a default X11 display ':0'.
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) This is generally not what you want.
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) You should probably use a higher display number just to avoid any confusion (and also this warning message).
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) X.Org X Server 1.19.0
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) Release Date: 2016-11-15
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) X Protocol Version 11, Revision 0
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) Current Operating System: Linux hexchat 4.8.15-grsec-amd64 #1 SMP Wed Dec 21 19:27:12 UTC 2016 x86_64
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) Kernel command line: BOOT_IMAGE=/vmlinuz-4.8.15-grsec-amd64 root=/dev/mapper/debian--vg-root ro initrd=/install/initrd.gz quiet splash apparmor=1 security=apparmor
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) Build Date: 23 November 2016  07:20:23PM
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) xorg-server 2:1.19.0-2 (https://www.debian.org/support)
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) Current version of pixman: 0.34.0
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server)         Before reporting problems, check http://wiki.x.org
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server)         to make sure that you have the latest version.
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) Markers: (--) probed, (**) from config file, (==) default setting,
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server)         (++) from command line, (!!) notice, (II) informational,
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server)         (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) (++) Log file: "/home/user/.xpra/Xorg.:0.log", Time: Tue Apr 18 02:44:12 2017
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) (++) Using config file: "/etc/xpra/xorg.conf"
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) (==) Using system config directory "/usr/share/X11/xorg.conf.d"
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) 2017-04-18 02:44:12,306 created unix domain socket: /home/user/.Xoz/hexchat/hexchat-0
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) 2017-04-18 02:44:12,843 Warning: all the compressors are disabled,
Apr 18 02:44:12 subgraph oz-daemon[1042]: 2017/04/18 02:44:12 [hexchat] (xpra-server) 2017-04-18 02:44:12,843  unless you have a gigabit connection or better, performance will suffer
Apr 18 02:44:13 subgraph oz-daemon[1042]: 2017/04/18 02:44:13 [hexchat] (xpra-server) 2017-04-18 02:44:13,063 Failed to launch ldconfig -p: [Errno 2] No such file or directory
Apr 18 02:44:13 subgraph oz-daemon[1042]: 2017/04/18 02:44:13 [hexchat] (xpra-server) 2017-04-18 02:44:13,416 D-Bus notification forwarding is available
Apr 18 02:44:13 subgraph oz-daemon[1042]: 2017/04/18 02:44:13 [hexchat] (xpra-server) 2017-04-18 02:44:13,418 xpra X11 version 0.17.6-r14322
Apr 18 02:44:13 subgraph oz-daemon[1042]: 2017/04/18 02:44:13 [hexchat] (xpra-server) 2017-04-18 02:44:13,418  running with pid 10 on Linux debian stretch/sid
Apr 18 02:44:13 subgraph oz-daemon[1042]: 2017/04/18 02:44:13 [hexchat] (xpra-server) 2017-04-18 02:44:13,418  on display :0
Apr 18 02:44:13 subgraph oz-daemon[1042]: 2017/04/18 02:44:13 [hexchat] (xpra-server) 2017-04-18 02:44:13,556 xpra is ready.
Apr 18 02:44:13 subgraph oz-daemon[1042]: 2017/04/18 02:44:13 [hexchat] XPRA started
Apr 18 02:44:13 subgraph oz-daemon[1042]: 2017/04/18 02:44:13 oz-init (hexchat) is ready
Apr 18 02:44:13 subgraph oz-daemon[1042]: 2017/04/18 02:44:13 [hexchat] Run program message received: &{Args:[--existing] Pwd:/home/user Path:/usr/bin/hexchat}
Apr 18 02:44:13 subgraph oz-daemon[1042]: 2017/04/18 02:44:13 [hexchat] Enabling seccomp whitelist for: /usr/bin-oz/hexchat
Apr 18 02:44:13 subgraph oz-daemon[1042]: 2017/04/18 02:44:13 [hexchat] (xpra-client-stderr) I /usr/bin/xpra [/usr/bin/xpra --no-daemon --mmap --no-sharing --bell --system-tray --xsettings --cursors --encoding=rgb --clipboard --no-microphone --no-speaker --notifications --title=@title@ --compress=0 --no-keyboard-sync --no-tray --socket-dir=/home/user/.Xoz/hexchat attach :0]
Apr 18 02:44:13 subgraph oz-daemon[1042]: 2017/04/18 02:44:13 [hexchat] (xpra-client-stderr) Warning: invalid option: 'html'
Apr 18 02:44:13 subgraph oz-daemon[1042]: 2017/04/18 02:44:13 [hexchat] (xpra-client-stderr) Gtk-Message: Failed to load module "gail"
Apr 18 02:44:13 subgraph oz-daemon[1042]: 2017/04/18 02:44:13 [hexchat] (xpra-client-stderr)
Apr 18 02:44:13 subgraph oz-daemon[1042]: 2017/04/18 02:44:13 [hexchat] (xpra-client-stderr) ** (xpra:2917): WARNING **: (bridge.c:998):atk_bridge_adaptor_init: runtime check failed: (root)
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:14,312 Warning: all the compressors are disabled,
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:14,312  unless you have a gigabit connection or better, performance will suffer
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:14,312 Xpra gtk2 client version 0.17.6-r14322
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:14,312  running on Linux debian stretch/sid
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:14,508 OpenGL support is missing:
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:14,508  cannot import name gdkgl
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-server) 2017-04-18 02:44:14,530 New unix-domain connection received on /home/user/.Xoz/hexchat/hexchat-0
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-server) 2017-04-18 02:44:14,530 New unix-domain connection received on /home/user/.Xoz/hexchat/hexchat-0
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:14,531  detected keyboard: rules=evdev, model=pc105, layout=us,us
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:14,532  desktop size is 3840x1080 with 1 screen:
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:14,532   :0.0 (1016x285 mm - DPI: 96x96) workarea: 3840x1053 at 0x27
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:14,532     monitor 1 1920x1080 (521x293 mm - DPI: 93x93)
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:14,532     monitor 2 1920x1080 at 1920x0 (521x293 mm - DPI: 93x93)
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-server) 2017-04-18 02:44:14,532 Connection lost
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:14,670 Warning: cannot query ICC profiles:
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:14,670  No module named PIL.ImageCms
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-server) 2017-04-18 02:44:14,753 Handshake complete; enabling connection
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-server) 2017-04-18 02:44:14,824 Python/Gtk2 Linux debian stretch/sid client version 0.17.6-r14322
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-server) 2017-04-18 02:44:14,824  connected from 'subgraph' as 'user' - 'User'
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-server) 2017-04-18 02:44:14,825  mmap is enabled using 256MB area in /home/user/.Xoz/hexchat/xpra.GvmzyF.mmap
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-server) 2017-04-18 02:44:14,828  client root window size is 3840x1080 with 1 display:
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-server) 2017-04-18 02:44:14,828   :0.0 (1016x285 mm - DPI: 96x96) workarea: 3840x1053 at 0x27
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-server) 2017-04-18 02:44:14,828     monitor 1 1920x1080 (521x293 mm - DPI: 93x93)
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-server) 2017-04-18 02:44:14,828     monitor 2 1920x1080 at 1920x0 (521x293 mm - DPI: 93x93)
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-server) 2017-04-18 02:44:14,945 server virtual display now set to 3840x1080
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-server) 2017-04-18 02:44:14,947 setting key repeat rate from client: 500ms delay / 30ms interval
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-server) 2017-04-18 02:44:14,950 setting keymap: rules=evdev, model=pc105, layout=us,us
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:14,998 enabled fast mmap transfers using 256MB shared memory area
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:14,999 Xpra X11 server version 0.17.6-r14322
Apr 18 02:44:14 subgraph oz-daemon[1042]: 2017/04/18 02:44:14 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:14,999  running on Linux debian stretch/sid
Apr 18 02:44:15 subgraph oz-daemon[1042]: 2017/04/18 02:44:15 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:15,000 Attached to :0 (press Control-C to detach)
Apr 18 02:44:15 subgraph oz-daemon[1042]: 2017/04/18 02:44:15 [hexchat] (xpra-client-stderr)
Apr 18 02:44:15 subgraph oz-daemon[1042]: 2017/04/18 02:44:15 [hexchat] (xpra-server) 2017-04-18 02:44:15,009 DPI set to 45 x 25 (wanted 96 x 96)
Apr 18 02:44:15 subgraph oz-daemon[1042]: 2017/04/18 02:44:15 [hexchat] (xpra-server) 2017-04-18 02:44:15,009  you may experience scaling problems, such as huge or small fonts, etc
Apr 18 02:44:15 subgraph oz-daemon[1042]: 2017/04/18 02:44:15 [hexchat] (xpra-server) 2017-04-18 02:44:15,009  to fix this issue, try the dpi switch, or use a patched Xorg dummy driver
Apr 18 02:44:15 subgraph oz-daemon[1042]: 2017/04/18 02:44:15 [hexchat] (xpra-server) 2017-04-18 02:44:15,047 python netifaces package is missing
Apr 18 02:44:15 subgraph oz-daemon[1042]: 2017/04/18 02:44:15 [hexchat] (xpra-server) 2017-04-18 02:44:15,052 Error during encoding:
Apr 18 02:44:15 subgraph oz-daemon[1042]: 2017/04/18 02:44:15 [hexchat] (xpra-server) Traceback (most recent call last):
Apr 18 02:44:15 subgraph oz-daemon[1042]: 2017/04/18 02:44:15 [hexchat] (xpra-server)   File "/usr/lib/python2.7/dist-packages/xpra/server/source.py", line 2100, in encode_loop
Apr 18 02:44:15 subgraph oz-daemon[1042]: 2017/04/18 02:44:15 [hexchat] (xpra-server)     fn_and_args[0](*fn_and_args[1:])
Apr 18 02:44:15 subgraph oz-daemon[1042]: 2017/04/18 02:44:15 [hexchat] (xpra-server)   File "/usr/lib/python2.7/dist-packages/xpra/server/window/window_source.py", line 561, in compress_and_send_window_icon
Apr 18 02:44:15 subgraph oz-daemon[1042]: 2017/04/18 02:44:15 [hexchat] (xpra-server)     assert wrapper.datatype in ("premult_argb32", "png")
Apr 18 02:44:15 subgraph oz-daemon[1042]: 2017/04/18 02:44:15 [hexchat] (xpra-server) AssertionError
Apr 18 02:44:17 subgraph oz-daemon[1042]: 2017/04/18 02:44:17 [hexchat] (xpra-server) 2017-04-18 02:44:17,067 Error during encoding:
Apr 18 02:44:17 subgraph oz-daemon[1042]: 2017/04/18 02:44:17 [hexchat] (xpra-server) Traceback (most recent call last):
Apr 18 02:44:17 subgraph oz-daemon[1042]: 2017/04/18 02:44:17 [hexchat] (xpra-server)   File "/usr/lib/python2.7/dist-packages/xpra/server/source.py", line 2100, in encode_loop
Apr 18 02:44:17 subgraph oz-daemon[1042]: 2017/04/18 02:44:17 [hexchat] (xpra-server)     fn_and_args[0](*fn_and_args[1:])
Apr 18 02:44:17 subgraph oz-daemon[1042]: 2017/04/18 02:44:17 [hexchat] (xpra-server)   File "/usr/lib/python2.7/dist-packages/xpra/server/window/window_source.py", line 561, in compress_and_send_window_icon
Apr 18 02:44:17 subgraph oz-daemon[1042]: 2017/04/18 02:44:17 [hexchat] (xpra-server)     assert wrapper.datatype in ("premult_argb32", "png")
Apr 18 02:44:17 subgraph oz-daemon[1042]: 2017/04/18 02:44:17 [hexchat] (xpra-server) AssertionError
Apr 18 02:44:25 subgraph audit[2918]: SECCOMP auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=2918 comm="hexchat" exe="/usr/bin-oz/hexchat" sig=31 arch=c000003e syscall=318 compat=0 ip=0x38e321ad119 code=0x0
Apr 18 02:44:37 subgraph oz-daemon[1042]: 2017/04/18 02:44:37 [hexchat] Recieved signal (interrupt)
Apr 18 02:44:37 subgraph oz-daemon[1042]: 2017/04/18 02:44:37 [hexchat] Child process pid=60 exited from init with status -1
Apr 18 02:44:37 subgraph oz-daemon[1042]: 2017/04/18 02:44:37 [hexchat] Shutting down sandbox after child exit.
Apr 18 02:44:37 subgraph oz-daemon[1042]: 2017/04/18 02:44:37 [hexchat] (xpra-server) 2017-04-18 02:44:37,337 New unix-domain connection received on /home/user/.Xoz/hexchat/hexchat-0
Apr 18 02:44:37 subgraph oz-daemon[1042]: 2017/04/18 02:44:37 [hexchat] (xpra-server) 2017-04-18 02:44:37,338 New unix-domain connection received on /home/user/.Xoz/hexchat/hexchat-0
Apr 18 02:44:37 subgraph oz-daemon[1042]: 2017/04/18 02:44:37 [hexchat] (xpra-server) 2017-04-18 02:44:37,340 Connection lost
Apr 18 02:44:37 subgraph oz-daemon[1042]: 2017/04/18 02:44:37 [hexchat] (xpra-server) 2017-04-18 02:44:37,712 Python2/GObject client version 0.17.6-r14322
Apr 18 02:44:37 subgraph oz-daemon[1042]: 2017/04/18 02:44:37 [hexchat] (xpra-server) 2017-04-18 02:44:37,713  connected from 'hexchat' as 'user' - 'User'
Apr 18 02:44:37 subgraph oz-daemon[1042]: 2017/04/18 02:44:37 [hexchat] (xpra-server) 2017-04-18 02:44:37,715 Shutting down in response to client request
Apr 18 02:44:37 subgraph oz-daemon[1042]: 2017/04/18 02:44:37 [hexchat] (xpra-server) 2017-04-18 02:44:37,715 Disconnecting client /home/user/.Xoz/hexchat/hexchat-0:
Apr 18 02:44:37 subgraph oz-daemon[1042]: 2017/04/18 02:44:37 [hexchat] (xpra-server) 2017-04-18 02:44:37,715  server shutdown
Apr 18 02:44:37 subgraph oz-daemon[1042]: 2017/04/18 02:44:37 [hexchat] (xpra-server) 2017-04-18 02:44:37,716 Disconnecting client /home/user/.Xoz/hexchat/hexchat-0:
Apr 18 02:44:37 subgraph oz-daemon[1042]: 2017/04/18 02:44:37 [hexchat] (xpra-server) 2017-04-18 02:44:37,717  server shutdown
Apr 18 02:44:37 subgraph oz-daemon[1042]: 2017/04/18 02:44:37 [hexchat] (xpra-client-stderr) 2017-04-18 02:44:37,722 server requested disconnect: server shutdown
Apr 18 02:44:37 subgraph oz-daemon[1042]: 2017/04/18 02:44:37 [hexchat] (xpra-server) 2017-04-18 02:44:37,722 xpra client disconnected.
Apr 18 02:44:38 subgraph oz-daemon[1042]: 2017/04/18 02:44:38 [hexchat] (xpra-server) 2017-04-18 02:44:38,725 xpra is terminating.
Apr 18 02:44:38 subgraph oz-daemon[1042]: 2017/04/18 02:44:38 [hexchat] (xpra-server) 2017-04-18 02:44:38,727 removing socket /home/user/.Xoz/hexchat/hexchat-0
Apr 18 02:44:38 subgraph oz-daemon[1042]: 2017/04/18 02:44:38 [hexchat] (xpra-server) 2017-04-18 02:44:38,727 killing xvfb with pid 21
Apr 18 02:44:38 subgraph oz-daemon[1042]: 2017/04/18 02:44:38 [hexchat] Child process pid=42 exited from init with status 0
Apr 18 02:44:38 subgraph oz-daemon[1042]: 2017/04/18 02:44:38 [hexchat] (xpra-server) (II) Server terminated successfully (0). Closing log file.
Apr 18 02:44:38 subgraph oz-daemon[1042]: 2017/04/18 02:44:38 [hexchat] Child process pid=10 exited from init with status 0
Apr 18 02:44:38 subgraph oz-daemon[1042]: 2017/04/18 02:44:38 [hexchat] (xpra stop) xpra at :0 has exited.
Apr 18 02:44:38 subgraph oz-daemon[1042]: 2017/04/18 02:44:38 [hexchat] oz-init exiting...
